### ISSUE TITLE
Sorting not working

### ISSUE THREAD

**Issue by Filifionka** [ChristofSchwarz/db_ext_guidedtour#3]
I am using a scenario where the guided tour shows step-by-step guide on which objects to use (focusing on specific sequence) in order to achieve a special kind of reporting. In this scenario the same filter needs to be used twice, but in separate steps. With the previous sort order functionality, I could add a "Order" field to the Guided tour table, and, thus, control which tip appears on which step of the tour. Now all tips referencing the same object appear one after another, essentially making the step-by-step guide not possible. I though the order in which I define the steps in the Guided Tour table would be respected, but regardless of where in the script I place the second tip for the filter, it would appear right after the first. 

Can you please add back the Sorting functionality?

Currently using licensed version 1.0.4. 

Thanks.

**Comment by ChristofSchwarz** [comment]
Sorting was changed in version 1.1.0 and it appears that the old settings, when the Guided Tour was created with an earlier version, still overrule the fix. The solution was to drag/drop the Guided Tour extension object over the existing and choose "Convert To" ...
